### ISSUE TITLE
Installation semi-fails 

### ISSUE THREAD

**Issue by umaxfun** [hatarist/homebrew-clickhouse#8]
```
==> cmake .. -DUSE_STATIC_LIBRARIES=0
==> make
Error: Failed to install plist file
Error: Calling <<-EOS.undent is disabled!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/hatarist/homebrew-clickhouse/clickhouse.rb:104:in `caveats'
Please report this to the hatarist/clickhouse tap!
Or, even better, submit a PR to fix it!
```

After that -- `brew services restart hatarist/clickhouse/clickhouse` leads to 

```
Stopping `clickhouse`... (might take a while)
==> Successfully stopped `clickhouse` (label: homebrew.mxcl.clickhouse)
Error: Calling <<-EOS.undent is disabled!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/hatarist/homebrew-clickhouse/clickhouse.rb:93:in `plist'
Please report this to the hatarist/clickhouse tap!
Or, even better, submit a PR to fix it! ```

**Comment by umaxfun** [comment]
I'd love to submit PR, but I know nothing about how brew works =(

**Comment by jacktang** [comment]
I have the same issue
